version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${DEV_DB_CONNECTION_PWD}"
      MYSQL_DATABASE: "${DEV_DB_NAME}"
    ports:
      - "3307:3306"

  tv-show-service:
    container_name: tv-show-service
    image: tv-show-service:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DEV_DB_URL: "${DEV_DB_URL}"
      DEV_DB_CONNECTION_USERNAME: "${DEV_DB_CONNECTION_USERNAME}"
      DEV_DB_CONNECTION_PWD: "${DEV_DB_CONNECTION_PWD}"
      DEV_JWT_SECRET: "${DEV_JWT_SECRET}"
      DEV_DUMMY_ADMIN_USERNAME: "${DEV_DUMMY_ADMIN_USERNAME}"
      DEV_DUMMY_ADMIN_EMAIL: "${DEV_DUMMY_ADMIN_EMAIL}"
      DEV_DUMMY_ADMIN_HASH_PWD: "${DEV_DUMMY_ADMIN_HASH_PWD}"
    depends_on:
      - mysql